FROM mysql:8

LABEL maintainer="devops@onix-systems.com"

RUN apt-get update && \
    apt-get install -y \
      gettext-base \
      git \
      netcat && \
    apt-get clean && \
    chown mysql:mysql /etc/mysql/conf.d/

CMD [ "--character-set-server=utf8", "--collation-server=utf8_general_ci" ]
