#
# MAINTAINER: devops@onix-systems.com
#
# This docker-compose helps to run MySQL master/slave replication architecture
#

version: "3"
services:

  master:
    hostname: "master"
    build:
      context: ./
      dockerfile: "Dockerfile.mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - CUSTOM_CONF_TEMPLATE=/etc/mysql/conf.d/custom.cnf.tmpl
      - CUSTOM_CONF=/etc/mysql/conf.d/custom.cnf
    volumes:
      - "./conf.d/master.cnf.tmpl:/etc/mysql/conf.d/custom.cnf.tmpl:ro"
      - "./db_scheme.sql:/docker-entrypoint-initdb.d/db_scheme.sql:ro"
      - "./scripts/master.sh:/docker-entrypoint-initdb.d/00-master.sh:ro"
      - "${DATA_FOLDER:-./data}/master/data:/var/lib/mysql"
      - "${DATA_FOLDER:-./data}/master/log:/var/log/mysql"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  slave:
    hostname: "slave"
    build:
      context: ./
      dockerfile: "Dockerfile.mysql"
    depends_on:
      - master
    links:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
      - MASTER_DB_HOST=master
      - SLAVE_USER=${SLAVE_USER:-slave_user}
      - SLAVE_USER_PASSWORD=${SLAVE_PASSWORD:-slave_password}
      - CUSTOM_CONF_TEMPLATE=/etc/mysql/conf.d/custom.cnf.tmpl
      - CUSTOM_CONF=/etc/mysql/conf.d/custom.cnf
    volumes:
      - "./conf.d/slave.cnf.tmpl:/etc/mysql/conf.d/custom.cnf.tmpl:ro"
      - "./scripts/slave.sh:/docker-entrypoint-initdb.d/00-slave.sh:ro"
      - "${DATA_FOLDER:-./data}/slave/data:/var/lib/mysql"
      - "${DATA_FOLDER:-./data}/slave/log:/var/log/mysql"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  configurator:
    hostname: "configurator"
    build:
      context: ./
      dockerfile: "Dockerfile.mysql"
    command: /configurator.sh
    depends_on:
      - master
      - slave
    environment:
      - MYSQL_USER=mysql
      - DATA_FOLDER=/data
    volumes:
      - "./scripts/configurator.sh:/configurator.sh:ro"
      - "${DATA_FOLDER:-./data}:/data"

  phpmyadmin:
    hostname: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    links:
      - master
      - slave
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=master,slave
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
